# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/sony/bahamut/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter bahamut,$(TARGET_DEVICE)),)

include $(CLEAR_VARS)
LOCAL_MODULE := SemcCameraUI-jniLibs64-xhdpi-release
LOCAL_MODULE_OWNER := sony
LOCAL_SRC_FILES := proprietary/priv-app/SemcCameraUI-xxhdpi-release/SemcCameraUI-xxhdpi-release.apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_SUFFIX := .apk
LOCAL_PRIVILEGED_MODULE := true
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := CameraAddonPermission
LOCAL_MODULE_OWNER := sony
LOCAL_SRC_FILES := proprietary/product/app/CameraAddonPermission/CameraAddonPermission.apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_SUFFIX := .apk
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := CameraCommonPermission
LOCAL_MODULE_OWNER := sony
LOCAL_SRC_FILES := proprietary/product/app/CameraCommonPermission/CameraCommonPermission.apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_SUFFIX := .apk
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := CameraExtensionnPermission
LOCAL_MODULE_OWNER := sony
LOCAL_SRC_FILES := proprietary/product/app/CameraExtensionnPermission/CameraExtensionnPermission.apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_SUFFIX := .apk
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := ImageProcessorPermission
LOCAL_MODULE_OWNER := sony
LOCAL_SRC_FILES := proprietary/product/app/ImageProcessorPermission/ImageProcessorPermission.apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_SUFFIX := .apk
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := CameraCommon
LOCAL_MODULE_OWNER := sony
LOCAL_SRC_FILES := proprietary/product/priv-app/CameraCommon/CameraCommon.apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_SUFFIX := .apk
LOCAL_PRIVILEGED_MODULE := true
include $(BUILD_PREBUILT)

endif
